# Generated by Django 4.2.26 on 2025-12-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mastergeouserscope'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masteruser',
            options={'managed': True},
        ),
    ]
