# Generated by Django 4.2.26 on 2025-12-15 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_masteruser_options'),
    ]

    operations = [
    ]
