# Generated by Django 4.2.26 on 2026-02-10 05:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_initial_master_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalApiAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=150)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('operation', models.CharField(choices=[('READ', 'READ'), ('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE')], max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('accessed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'audit_global_api',
                'indexes': [models.Index(fields=['api_id'], name='audit_globa_api_id_42a28b_idx'), models.Index(fields=['endpoint'], name='audit_globa_endpoin_5d1a7f_idx'), models.Index(fields=['accessed_at'], name='audit_globa_accesse_6903fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='AppApiAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('operation', models.CharField(choices=[('READ', 'READ'), ('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE')], max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.masteruser')),
            ],
            options={
                'db_table': 'audit_app_api',
                'indexes': [models.Index(fields=['user'], name='audit_app_a_user_id_ba9612_idx'), models.Index(fields=['endpoint'], name='audit_app_a_endpoin_00d4c3_idx'), models.Index(fields=['created_at'], name='audit_app_a_created_9104f8_idx')],
            },
        ),
    ]
