# Generated by Django 4.2.26 on 2026-06-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteendetail',
            name='packaged_products_list',
            field=models.TextField(blank=True, help_text='If yes, please list the products.', null=True),
        ),
        migrations.AddField(
            model_name='canteendetail',
            name='training_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='canteendetail',
            name='training_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
