# Generated by Django 4.2.26 on 2026-07-10 08:59

from django.db import migrations, models
import django.db.models.deletion
import support.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=support.models.generate_custom_th_urid, editable=False, max_length=36)),
                ('ticket_code', models.CharField(default=support.models.generate_ticket_code, editable=False, max_length=20, unique=True, verbose_name='Ticket Code')),
                ('is_solved', models.BooleanField(default=False, verbose_name='Is Solved?')),
                ('pmu_response', models.TextField(verbose_name='PMU IT Resposne')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('master_user', models.ForeignKey(blank=True, db_column='user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grievance_user', to='core.masteruser')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=support.models.generate_custom_th_urid, editable=False, max_length=36)),
                ('screenshot', models.ImageField(upload_to='support_tickets/screenshots/', verbose_name='Screenshot')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_media', to='support.ticket', verbose_name='Ticket')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=support.models.generate_custom_th_urid, editable=False, max_length=36)),
                ('username', models.CharField(max_length=150, verbose_name='Username')),
                ('problem_message', models.TextField(verbose_name='Problem Message')),
                ('mobile_no', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.masterblock', verbose_name='Block')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.masterdistrict', verbose_name='District')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_body', to='support.ticket', verbose_name='Ticket')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
