# Generated by Django 4.2.26 on 2026-09-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AspirationalBlockAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='Financial Year (e.g., 2026-27)', max_length=10)),
                ('month', models.IntegerField(help_text='Month Code (1-12)')),
                ('div_code', models.CharField(default='00', max_length=10)),
                ('dist_code', models.CharField(max_length=10)),
                ('block_code', models.CharField(max_length=10)),
                ('prog_code', models.CharField(help_text='Indicator Code (0511 or 0512)', max_length=10)),
                ('prog_head_code', models.CharField(max_length=10)),
                ('unit', models.CharField(help_text='Number or Percentage', max_length=50)),
                ('period_name_id', models.CharField(max_length=10)),
                ('lead_dept_name_id', models.CharField(max_length=10)),
                ('mon_ach_numerator', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('mon_ach_denominator', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('mon_ach', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('cum_ach', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('quarter_month', models.CharField(blank=True, max_length=50, null=True)),
                ('six_monthly', models.CharField(blank=True, max_length=50, null=True)),
                ('four_month', models.CharField(blank=True, max_length=50, null=True)),
                ('disclaimer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-month', 'dist_code', 'block_code'],
                'unique_together': {('year', 'month', 'dist_code', 'block_code', 'prog_code')},
            },
        ),
    ]
