# Generated by Django 4.2.26 on 2026-01-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LDMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blcc_meeting_list',
            name='notif_date',
            field=models.TextField(db_column='meeting_notification_date'),
        ),
        migrations.AlterField(
            model_name='dlcc_meeting_list',
            name='notif_date',
            field=models.TextField(db_column='meeting_notification_date'),
        ),
    ]
