# Generated by Django 4.2.26 on 2026-01-21 07:56

import LDMS.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0013_batchreport'),
        ('LDMS', '0002_alter_blcc_meeting_list_notif_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportbucket',
            name='training_plan',
        ),
        migrations.RemoveField(
            model_name='supportbucket',
            name='training_theme',
        ),
        migrations.CreateModel(
            name='TrainingSupport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=LDMS.models.generate_custom_th_urid, editable=False, max_length=36)),
                ('id', models.AutoField(db_column='training_support_id', primary_key=True, serialize=False)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('support_bucket', models.ForeignKey(db_column='support_bucket_id', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='LDMS.supportbucket')),
                ('training_plan', models.ForeignKey(db_column='training_plan_id', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='TMS.trainingplan')),
                ('training_theme', models.ForeignKey(db_column='training_theme_id', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='TMS.trainingtheme')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'verbose_name': 'Training Support',
                'verbose_name_plural': 'Training Supports',
                'db_table': 'ldms_training_support',
            },
        ),
        migrations.CreateModel(
            name='SBtypes',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=LDMS.models.generate_custom_th_urid, editable=False, max_length=36)),
                ('id', models.AutoField(db_column='sbtypes_id', primary_key=True, serialize=False)),
                ('bucket_type', models.CharField(db_column='bucket_type', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'verbose_name': 'Support Bucket Type',
                'verbose_name_plural': 'Support Bucket Types',
                'db_table': 'ldms_sbtypes',
            },
        ),
        migrations.AddField(
            model_name='supportbucket',
            name='bucket_type',
            field=models.ForeignKey(blank=True, db_column='bucket_type_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='LDMS.sbtypes'),
        ),
    ]
