# Generated by Django 4.2.26 on 2026-01-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LDMS', '0003_remove_supportbucket_training_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='assistance',
            field=models.TextField(blank=True, db_column='assistance', null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='code',
            field=models.CharField(blank=True, db_column='code', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='contact_point',
            field=models.TextField(blank=True, db_column='contact_point', null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='elligibility',
            field=models.TextField(blank=True, db_column='elligibility', null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='funding',
            field=models.TextField(blank=True, db_column='funding', null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='scope',
            field=models.TextField(blank=True, db_column='scope', null=True),
        ),
    ]
