# Generated by Django 4.2.26 on 2026-01-26 06:54

import LDMS.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LDMS', '0004_scheme_assistance_scheme_code_scheme_contact_point_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='State_Analytics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=LDMS.models.generate_custom_th_urid, editable=False, max_length=36)),
                ('id', models.AutoField(db_column='state_analytics_id', primary_key=True, serialize=False)),
                ('total_vos', models.CharField(blank=True, db_column='total_vos', max_length=255, null=True)),
                ('total_clfs', models.TextField(blank=True, db_column='total_clfs', null=True)),
                ('total_shgs', models.TextField(blank=True, db_column='total_shgs', null=True)),
                ('total_rural_hh', models.TextField(blank=True, db_column='total_rural_hh', null=True)),
                ('total_hh_under_shgs', models.TextField(blank=True, db_column='total_hh_under_shgs', null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'verbose_name': 'State Analytics',
                'verbose_name_plural': 'State Analytics Records',
                'db_table': 'ldms_state_analytics',
            },
        ),
        migrations.CreateModel(
            name='District_Analytics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=LDMS.models.generate_custom_th_urid, editable=False, max_length=36)),
                ('id', models.AutoField(db_column='dist_analytics_id', primary_key=True, serialize=False)),
                ('total_vos', models.CharField(blank=True, db_column='total_vos', max_length=255, null=True)),
                ('total_clfs', models.TextField(blank=True, db_column='total_clfs', null=True)),
                ('total_shgs', models.TextField(blank=True, db_column='total_shgs', null=True)),
                ('total_rural_hh', models.TextField(blank=True, db_column='total_rural_hh', null=True)),
                ('total_hh_under_shgs', models.TextField(blank=True, db_column='total_hh_under_shgs', null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('district', models.ForeignKey(db_column='district_id', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='core.masterdistrict')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'verbose_name': 'District Analytics',
                'verbose_name_plural': 'District Analytics Records',
                'db_table': 'ldms_district_analytics',
            },
        ),
        migrations.CreateModel(
            name='Block_Analytics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=LDMS.models.generate_custom_th_urid, editable=False, max_length=36)),
                ('id', models.AutoField(db_column='block_analytics_id', primary_key=True, serialize=False)),
                ('total_vos', models.CharField(blank=True, db_column='total_vos', max_length=255, null=True)),
                ('total_shgs', models.TextField(blank=True, db_column='total_shgs', null=True)),
                ('total_rural_hh', models.TextField(blank=True, db_column='total_rural_hh', null=True)),
                ('total_hh_under_shgs', models.TextField(blank=True, db_column='total_hh_under_shgs', null=True)),
                ('block', models.ForeignKey(db_column='block_id', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='core.masterblock')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'verbose_name': 'Block Analytics',
                'verbose_name_plural': 'Block Analytics Records',
                'db_table': 'ldms_block_analytics',
            },
        ),
    ]
