# Generated by Django 4.2.26 on 2026-01-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LDMS', '0005_state_analytics_district_analytics_block_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='block_analytics',
            name='total_clfs',
            field=models.TextField(blank=True, db_column='total_clfs', null=True),
        ),
    ]
