# Generated by Django 4.2.26 on 2026-01-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LDMS', '0006_block_analytics_total_clfs'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorded_benefs',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recorded_benefs',
            name='religion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
