# Generated by Django 4.2.26 on 2026-01-28 09:00

import LDMS.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LDMS', '0007_recorded_benefs_designation_recorded_benefs_religion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket_Approval',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=LDMS.models.generate_custom_th_urid, editable=False, max_length=36)),
                ('id', models.AutoField(db_column='bucket_approval_id', primary_key=True, serialize=False)),
                ('approval_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_column='approval_status', default='DRAFT', max_length=50)),
                ('rejection_reason', models.TextField(blank=True, db_column='rejection_reason', null=True)),
                ('approval_date', models.DateField(db_column='approval_date')),
                ('approved_by', models.ForeignKey(blank=True, db_column='approved_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('support_bucket', models.ForeignKey(db_column='support_bucket_id', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='LDMS.supportbucket')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'verbose_name': 'Bucket Approval',
                'verbose_name_plural': 'Bucket Approvals',
                'db_table': 'ldms_bucket_approval',
            },
        ),
    ]
