# Generated by Django 4.2.26 on 2026-01-28 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LDMS', '0008_bucket_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket_approval',
            name='block_id',
            field=models.ForeignKey(blank=True, db_column='block_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.masterblock'),
        ),
        migrations.AddField(
            model_name='bucket_approval',
            name='panchayat_id',
            field=models.ForeignKey(blank=True, db_column='panchayat_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.masterpanchayat'),
        ),
    ]
