# Generated by Django 4.2.26 on 2026-01-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LDMS', '0009_bucket_approval_block_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket_approval',
            name='approval_date',
            field=models.DateField(blank=True, db_column='approval_date', null=True),
        ),
    ]
