# Generated by Django 4.2.26 on 2026-01-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LDMS', '0010_alter_bucket_approval_approval_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportbucket',
            name='benefit_amount',
            field=models.DecimalField(blank=True, db_column='benefit_amount', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='supportbucket',
            name='benefit_name',
            field=models.CharField(blank=True, db_column='benefit_name', max_length=255, null=True),
        ),
    ]
