# Generated by Django 4.2.26 on 2026-05-02 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LDMS', '0011_alter_supportbucket_benefit_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dlcc_meeting_list',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='dlcc_meeting_list',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='dlcc_meeting_list',
            name='district',
        ),
        migrations.RemoveField(
            model_name='dlcc_meeting_list',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='blcc_meeting',
            name='blcc_meeting_list',
        ),
        migrations.RemoveField(
            model_name='dlcc_meeting',
            name='dlcc_meeting_list',
        ),
        migrations.AddField(
            model_name='blcc_meeting',
            name='district',
            field=models.ForeignKey(blank=True, db_column='district_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.masterdistrict'),
        ),
        migrations.AddField(
            model_name='dlcc_meeting',
            name='district',
            field=models.ForeignKey(db_column='district_id', db_constraint=False, default=None, on_delete=django.db.models.deletion.PROTECT, to='core.masterdistrict'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BLCC_Meeting_List',
        ),
        migrations.DeleteModel(
            name='DLCC_Meeting_List',
        ),
    ]
