# Generated by Django 4.2.26 on 2026-05-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epSakhi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseloandetail',
            name='department',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseloandetail',
            name='institution_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseproduct',
            name='activity_or_product_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseproduct',
            name='sales_area',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseshop',
            name='sales_area',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseshop',
            name='shop_category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseshop',
            name='shop_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseshop',
            name='source_of_inventory',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enterprisesubsidydetail',
            name='subsidy_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enterprisesubsidydetail',
            name='subsidy_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enterprisesupport',
            name='other_support',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enterprisesupport',
            name='support_category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enterprisesupport',
            name='support_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enterprisesupport',
            name='support_sub_category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enterprisetrainingreq',
            name='department',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enterprisetrainingreq',
            name='duration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enterprisetrainingreq',
            name='expected_income',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enterprisetrainingreq',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enterprisetrainingreq',
            name='sector',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enterprisetrainingreq',
            name='sector_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enterprisetrainingreq',
            name='training_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='existingenterprise',
            name='is_support_required',
            field=models.TextField(blank=True, null=True),
        ),
    ]
