# Generated by Django 4.2.26 on 2025-11-15 20:44

from django.db import migrations, models
import epSakhi.models


class Migration(migrations.Migration):

    dependencies = [
        ('epSakhi', '0002_beneficiaryrecorded_enterpriseloandetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crpeptopanchayat',
            name='TH_urid',
            field=models.CharField(db_column='TH_urid', default=epSakhi.models.generate_custom_th_urid, editable=False, max_length=36),
        ),
    ]
