# Generated by Django 4.2.26 on 2026-05-27 07:51

from django.db import migrations, models
import django.db.models.deletion
import epSakhi.models


class Migration(migrations.Migration):

    dependencies = [
        ('epSakhi', '0002_alter_enterpriseloandetail_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOU',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', db_index=True, default=epSakhi.models.generate_custom_th_urid, editable=False, max_length=36, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mou_status', models.CharField(blank=True, max_length=255, null=True)),
                ('mou_date', models.DateField(blank=True, null=True)),
                ('mou_duration', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'db_table': 'epSakhi_mou',
            },
        ),
        migrations.CreateModel(
            name='MOUEnterprise',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', db_index=True, default=epSakhi.models.generate_custom_th_urid, editable=False, max_length=36, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lokos_shg_code', models.CharField(blank=True, db_column='lokos_shg_code', max_length=100, null=True)),
                ('lokos_shg_name', models.CharField(blank=True, db_column='lokos_shg_name', max_length=255, null=True)),
                ('lokos_clf_code', models.CharField(blank=True, db_column='lokos_clf_code', max_length=100, null=True)),
                ('lokos_clf_name', models.CharField(blank=True, db_column='lokos_clf_name', max_length=255, null=True)),
                ('enterprise_name', models.CharField(blank=True, max_length=255, null=True)),
                ('entrepreneur_name', models.CharField(blank=True, max_length=255, null=True)),
                ('entrepreneur_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('entrepeneur_picture', models.ImageField(blank=True, null=True, upload_to='epSakhi/media/mou/entrepreneurs/%Y/%m/')),
                ('block', models.ForeignKey(blank=True, db_column='block_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.masterblock')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('district', models.ForeignKey(blank=True, db_column='district_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.masterdistrict')),
                ('panchayat', models.ForeignKey(blank=True, db_column='panchayat_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.masterpanchayat')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'db_table': 'epSakhi_mouEnterprise',
            },
        ),
        migrations.CreateModel(
            name='MOUTraders',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', db_index=True, default=epSakhi.models.generate_custom_th_urid, editable=False, max_length=36, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trader_name', models.CharField(blank=True, max_length=255, null=True)),
                ('trader_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traders', to='epSakhi.mouenterprise')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'db_table': 'epSakhi_mouTraders',
            },
        ),
        migrations.CreateModel(
            name='MOUSales',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', db_index=True, default=epSakhi.models.generate_custom_th_urid, editable=False, max_length=36, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('est_monthly_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('est_annual_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('supply_frequency', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='epSakhi.mouenterprise')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'db_table': 'epSakhi_mouSales',
            },
        ),
        migrations.CreateModel(
            name='MOUProducts',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', db_index=True, default=epSakhi.models.generate_custom_th_urid, editable=False, max_length=36, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='epSakhi.mouenterprise')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'db_table': 'epSakhi_mouProducts',
            },
        ),
        migrations.CreateModel(
            name='MOUProdCategories',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', db_index=True, default=epSakhi.models.generate_custom_th_urid, editable=False, max_length=36, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('parent_category', models.CharField(blank=True, max_length=255, null=True)),
                ('child_category', models.CharField(blank=True, max_length=255, null=True)),
                ('MOUProdID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_categories', to='epSakhi.mouproducts')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'db_table': 'epSakhi_mouProdCategories',
            },
        ),
        migrations.CreateModel(
            name='MOUOrg',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', db_index=True, default=epSakhi.models.generate_custom_th_urid, editable=False, max_length=36, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('buyer_org_name', models.CharField(blank=True, max_length=255, null=True)),
                ('org_address', models.TextField(blank=True, null=True)),
                ('org_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_orgs', to='epSakhi.mouenterprise')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'db_table': 'epSakhi_mouProdBuyOrg',
            },
        ),
        migrations.CreateModel(
            name='MOUDocs',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', db_index=True, default=epSakhi.models.generate_custom_th_urid, editable=False, max_length=36, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('doc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_file', models.FileField(blank=True, null=True, upload_to='epSakhi/media/mou/docs/%Y/%m/')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('mou_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mou_docs', to='epSakhi.mou')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'db_table': 'epSakhi_mouDocs',
            },
        ),
        migrations.AddField(
            model_name='mou',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mous', to='epSakhi.mouenterprise'),
        ),
        migrations.AddField(
            model_name='mou',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser'),
        ),
        migrations.CreateModel(
            name='ErrorDB',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', db_index=True, default=epSakhi.models.generate_custom_th_urid, editable=False, max_length=36, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('error_code', models.CharField(max_length=255)),
                ('error_message', models.TextField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'db_table': 'epSakhi_errorDB',
            },
        ),
    ]
