# Generated by Django 4.2.26 on 2025-11-23 11:33

from django.db import migrations, models
import django.db.models.deletion
import epSakhi.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mastergeouserscope'),
        ('epSakhi', '0003_alter_crpeptopanchayat_th_urid'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseProduct',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=epSakhi.models.generate_custom_th_urid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('enterprise_id', models.CharField(db_column='enterprise_id', help_text='TH_urid of enterprise form (existing/new)', max_length=36)),
                ('main_product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_or_product_type', models.CharField(blank=True, max_length=255, null=True)),
                ('product_features', models.TextField(blank=True, null=True)),
                ('production_capacity', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_material', models.TextField(blank=True, null=True)),
                ('machinery_equipment', models.TextField(blank=True, null=True)),
                ('sales_area', models.CharField(blank=True, max_length=255, null=True)),
                ('target_customers', models.TextField(blank=True, null=True)),
                ('packaging_branding_status', models.CharField(blank=True, max_length=255, null=True)),
                ('marketing_strategy', models.TextField(blank=True, null=True)),
                ('marketing_channels', models.TextField(blank=True, null=True)),
                ('marketing_challenges', models.TextField(blank=True, null=True)),
                ('market_linkage', models.TextField(blank=True, null=True)),
                ('accept_digital_payment', models.BooleanField(default=False)),
                ('avg_monthly_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'db_table': 'epSakhi_exEpProduct',
            },
        ),
        migrations.CreateModel(
            name='EnterpriseSubsidyDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=epSakhi.models.generate_custom_th_urid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('enterprise_id', models.CharField(db_column='enterprise_id', help_text='TH_urid of enterprise form (existing/new)', max_length=36)),
                ('subsidy_type', models.CharField(blank=True, max_length=255, null=True)),
                ('subsidy_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subsidy_detail', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'db_table': 'epSakhi_exEpSubsidy',
            },
        ),
        migrations.CreateModel(
            name='EnterpriseTypeCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=epSakhi.models.generate_custom_th_urid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('form_type', models.CharField(blank=True, help_text='existing/new/none', max_length=20, null=True)),
                ('enterprise_id', models.CharField(db_column='enterprise_id', help_text='TH_urid of enterprise form (existing/new)', max_length=36)),
                ('parent_category', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'db_table': 'epSakhi_epType',
            },
        ),
        migrations.CreateModel(
            name='NoEnterpriseForm',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=epSakhi.models.generate_custom_th_urid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('recorded_benef_id', models.CharField(db_column='recorded_benef_id', max_length=36)),
                ('if_shg_member_inv', models.BooleanField(default=False, help_text='Is SHG member involved in any EP/wage activity')),
                ('no_int_reason', models.TextField(blank=True, null=True)),
                ('is_training_required', models.BooleanField(default=False)),
                ('future_willing', models.BooleanField(default=False)),
                ('has_shg_cif', models.BooleanField(default=False)),
                ('cif_fund_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'db_table': 'epSakhi_noEpForm',
            },
        ),
        migrations.CreateModel(
            name='NoEnterpriseWage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=epSakhi.models.generate_custom_th_urid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('enterprise_id', models.CharField(db_column='enterprise_id', help_text='Link to TH_urid (could be NoEnterpriseForm / other form as per design)', max_length=36)),
                ('placement_sector', models.CharField(blank=True, max_length=255, null=True)),
                ('type_of_emp', models.CharField(blank=True, max_length=255, null=True)),
                ('exp_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('location_scope', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'db_table': 'epSakhi_noEpWage',
            },
        ),
        migrations.RenameField(
            model_name='enterprisetrainingreq',
            old_name='any_specific_department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='enterprisetrainingreq',
            old_name='any_specific_scheme',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='enterprisetrainingreq',
            old_name='skill_name',
            new_name='sector',
        ),
        migrations.RenameField(
            model_name='enterprisetrainingreq',
            old_name='training_type',
            new_name='training_module_name',
        ),
        migrations.RenameField(
            model_name='existingenterprise',
            old_name='can_send_to_bijnor_clf',
            new_name='can_send_to_bijnor',
        ),
        migrations.RenameField(
            model_name='existingenterprise',
            old_name='activity_or_product_type',
            new_name='digital_emarket_support',
        ),
        migrations.RenameField(
            model_name='existingenterprise',
            old_name='has_received_any_scheme_support',
            new_name='has_receieved_subsidy',
        ),
        migrations.RenameField(
            model_name='existingenterprise',
            old_name='certification_registration',
            new_name='industry_loc',
        ),
        migrations.RenameField(
            model_name='existingenterprise',
            old_name='financial_coordination',
            new_name='info_abt_gov_scheme',
        ),
        migrations.RenameField(
            model_name='existingenterprise',
            old_name='enterprise_type',
            new_name='infrastructure_support',
        ),
        migrations.RenameField(
            model_name='existingenterprise',
            old_name='main_product_name',
            new_name='is_equip_req',
        ),
        migrations.RenameField(
            model_name='existingenterprise',
            old_name='packaging_branding_status',
            new_name='is_promo_ad_req',
        ),
        migrations.RenameField(
            model_name='existingenterprise',
            old_name='sales_area',
            new_name='market_branding_support',
        ),
        migrations.RenameField(
            model_name='existingenterprise',
            old_name='production_capacity',
            new_name='mentorship_support',
        ),
        migrations.RenameField(
            model_name='existingenterprise',
            old_name='transportation_facility',
            new_name='nearest_industry',
        ),
        migrations.RenameField(
            model_name='existingenterprise',
            old_name='number_of_employees',
            new_name='number_of_shg_emp',
        ),
        migrations.RenameField(
            model_name='existingenterprise',
            old_name='machinery_equipment',
            new_name='other_support',
        ),
        migrations.RenameField(
            model_name='newenterprise',
            old_name='req_branding',
            new_name='digital_emarket_support',
        ),
        migrations.RenameField(
            model_name='newenterprise',
            old_name='req_credit_linkage',
            new_name='has_shg_cif',
        ),
        migrations.RenameField(
            model_name='newenterprise',
            old_name='any_past_experience',
            new_name='infrastructure_support_detail',
        ),
        migrations.RenameField(
            model_name='newenterprise',
            old_name='family_member_ep_details',
            new_name='is_promo_ad_req_detail',
        ),
        migrations.RenameField(
            model_name='newenterprise',
            old_name='req_digi_emarket_linkage',
            new_name='is_training_received',
        ),
        migrations.RenameField(
            model_name='newenterprise',
            old_name='req_ep_development_training',
            new_name='is_training_required',
        ),
        migrations.RenameField(
            model_name='newenterprise',
            old_name='skills_present',
            new_name='market_linkage_detail',
        ),
        migrations.RenameField(
            model_name='newenterprise',
            old_name='training_required',
            new_name='other_support',
        ),
        migrations.RemoveField(
            model_name='existingenterprise',
            name='marketing_challenges',
        ),
        migrations.RemoveField(
            model_name='existingenterprise',
            name='marketing_channels',
        ),
        migrations.RemoveField(
            model_name='existingenterprise',
            name='marketing_strategy',
        ),
        migrations.RemoveField(
            model_name='existingenterprise',
            name='monthly_sales',
        ),
        migrations.RemoveField(
            model_name='existingenterprise',
            name='product_features',
        ),
        migrations.RemoveField(
            model_name='existingenterprise',
            name='profit_percentage',
        ),
        migrations.RemoveField(
            model_name='existingenterprise',
            name='raw_material',
        ),
        migrations.RemoveField(
            model_name='existingenterprise',
            name='skills_acquired',
        ),
        migrations.RemoveField(
            model_name='existingenterprise',
            name='target_customers',
        ),
        migrations.RemoveField(
            model_name='existingenterprise',
            name='training_details',
        ),
        migrations.RemoveField(
            model_name='newenterprise',
            name='req_financial_assistance',
        ),
        migrations.RemoveField(
            model_name='newenterprise',
            name='req_infra_support',
        ),
        migrations.RemoveField(
            model_name='newenterprise',
            name='req_market_linkage',
        ),
        migrations.RemoveField(
            model_name='newenterprise',
            name='req_skill_training',
        ),
        migrations.AddField(
            model_name='beneficiaryrecorded',
            name='enterprise_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beneficiaryrecorded',
            name='special_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enterpriseloandetail',
            name='form_type',
            field=models.CharField(blank=True, help_text='existing/new/other', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='enterprisemedia',
            name='form_type',
            field=models.CharField(blank=True, help_text='existing/new/other', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='enterprisetrainingreq',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enterprisetrainingreq',
            name='expected_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='enterprisetrainingreq',
            name='form_type',
            field=models.CharField(blank=True, help_text='existing/new/other', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='existingenterprise',
            name='cif_fund_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='existingenterprise',
            name='gross_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='existingenterprise',
            name='has_shg_cif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='existingenterprise',
            name='is_training_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='existingenterprise',
            name='nearest_skill_centre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='existingenterprise',
            name='owner_special_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='existingenterprise',
            name='skill_centre_loc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='existingenterprise',
            name='total_emp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='existingenterprise',
            name='transportation_availability',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='existingenterprise',
            name='uddyam_aadhar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newenterprise',
            name='applicant_special_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newenterprise',
            name='cif_fund_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='newenterprise',
            name='financial_support',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newenterprise',
            name='industry_loc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newenterprise',
            name='infrastructure_support_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newenterprise',
            name='is_promo_ad_req_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newenterprise',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='newenterprise',
            name='market_linkage_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newenterprise',
            name='mentorship_support',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newenterprise',
            name='nearest_industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newenterprise',
            name='nearest_skill_centre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newenterprise',
            name='prefered_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newenterprise',
            name='skill_centre_loc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseloandetail',
            name='enterprise_id',
            field=models.CharField(db_column='enterprise_id', help_text='TH_urid of enterprise form (existing/new)', max_length=36),
        ),
        migrations.AlterField(
            model_name='enterprisemedia',
            name='enterprise_id',
            field=models.CharField(db_column='enterprise_id', help_text='TH_urid of enterprise form (existing/new)', max_length=36),
        ),
        migrations.AlterField(
            model_name='enterprisetrainingreq',
            name='enterprise_id',
            field=models.CharField(db_column='enterprise_id', help_text='TH_urid of enterprise form (existing/new)', max_length=36),
        ),
        migrations.AlterField(
            model_name='existingenterprise',
            name='electricity_available',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='existingenterprise',
            name='need_transport_help',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='existingenterprise',
            name='water_available',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='enterprisetrainingreq',
            table='epSakhi_epTraining',
        ),
        migrations.DeleteModel(
            name='EnterpriseSupportDetail',
        ),
    ]
