# Generated by Django 4.2.26 on 2026-05-28 06:45

from django.db import migrations, models
import django.db.models.deletion
import epSakhi.models


class Migration(migrations.Migration):

    dependencies = [
        ('epSakhi', '0003_mou_mouenterprise_moutraders_mousales_mouproducts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistMOUTarget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', db_index=True, default=epSakhi.models.generate_custom_th_urid, editable=False, max_length=36, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mou_target', models.IntegerField(blank=True, null=True)),
                ('achieved_mou', models.IntegerField(blank=True, null=True)),
                ('financial_year', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('district', models.ForeignKey(blank=True, db_column='district_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.masterdistrict')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'db_table': 'epSakhi_distMOUTarget',
            },
        ),
    ]
