# Generated by Django 4.2.26 on 2025-11-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epSakhi', '0004_enterpriseproduct_enterprisesubsidydetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noenterpriseform',
            name='if_shg_member_inv',
            field=models.TextField(blank=True, help_text='Is SHG member involved in any EP/wage activity', null=True),
        ),
    ]
