# Generated by Django 4.2.26 on 2026-05-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epSakhi', '0004_distmoutarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouenterprise',
            name='lokos_vo_code',
            field=models.CharField(blank=True, db_column='lokos_vo_code', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mouenterprise',
            name='lokos_vo_name',
            field=models.CharField(blank=True, db_column='lokos_vo_name', max_length=255, null=True),
        ),
    ]
