# Generated by Django 4.2.26 on 2026-05-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epSakhi', '0005_mouenterprise_lokos_vo_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouenterprise',
            name='enterprise_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
