# Generated by Django 4.2.26 on 2025-11-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epSakhi', '0005_alter_noenterpriseform_if_shg_member_inv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisetrainingreq',
            name='training_module_name',
            field=models.TextField(blank=True, help_text='Parent: Child for sectors', null=True),
        ),
    ]
