# Generated by Django 4.2.26 on 2025-11-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epSakhi', '0006_alter_enterprisetrainingreq_training_module_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisetrainingreq',
            name='expected_income',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='noenterprisewage',
            name='exp_salary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
