# Generated by Django 4.2.26 on 2026-05-28 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epSakhi', '0006_mouenterprise_enterprise_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouenterprise',
            name='village',
            field=models.ForeignKey(blank=True, db_column='village_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.mastervillage'),
        ),
    ]
