# Generated by Django 4.2.26 on 2026-06-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epSakhi', '0007_mouenterprise_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='mou',
            name='mou_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
