# Generated by Django 4.2.26 on 2025-11-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epSakhi', '0007_alter_enterprisetrainingreq_expected_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisetypecategory',
            name='parent_category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enterprisetypecategory',
            name='sub_category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
