# Generated by Django 4.2.26 on 2026-06-30 12:41

from django.db import migrations, models
import django.db.models.deletion
import epSakhi.models


class Migration(migrations.Migration):

    dependencies = [
        ('epSakhi', '0008_mou_mou_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingCRPTargets',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', db_index=True, default=epSakhi.models.generate_custom_th_urid, editable=False, max_length=36, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_count', models.PositiveIntegerField(default=0, verbose_name='Target count (crps)')),
                ('financial_year', models.CharField(blank=True, max_length=9, null=True, verbose_name='Financial year')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crpmap_district_target', to='core.masterdistrict')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'db_table': 'epSakhi_crpmap_targets',
                'managed': True,
                'indexes': [models.Index(fields=['district'], name='epSakhi_crp_distric_e02793_idx'), models.Index(fields=['financial_year'], name='epSakhi_crp_financi_8f73a7_idx')],
            },
        ),
    ]
