# Generated by Django 4.2.26 on 2025-11-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epSakhi', '0008_alter_enterprisetypecategory_parent_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseloandetail',
            name='loan_amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
