# Generated by Django 4.2.26 on 2025-11-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epSakhi', '0009_alter_enterpriseloandetail_loan_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newenterprise',
            name='loan_amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
