# Generated by Django 4.2.26 on 2026-01-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epSakhi', '0010_alter_newenterprise_loan_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryrecorded',
            name='pld_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
