# Generated by Django 4.2.26 on 2025-12-03 11:49

import TMS.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mastergeouserscope'),
        ('TMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchClosureRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=TMS.models.generate_custom_th_urid, editable=False, max_length=36)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('certificates_issued', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tms_batchclosurerequest',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BatchCost',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=TMS.models.generate_custom_th_urid, editable=False, max_length=36)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trainer_part_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tp_part_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'db_table': 'tms_batchcost',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BatchMasterTrainer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=TMS.models.generate_custom_th_urid, editable=False, max_length=36)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('participated', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tms_batchmastertrainer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BatchMedia',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=TMS.models.generate_custom_th_urid, editable=False, max_length=36)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('FOODING', 'Fooding'), ('CLASS', 'Classroom'), ('TRAINING', 'Pictures with Ongoing Training'), ('PARTICIPANTS', 'Pictures with all Participants'), ('ATTENDANCE', 'Pictures while Attendance'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('file', models.FileField(blank=True, help_text='Upload image (jpeg/png) or a PDF containing required photos.', null=True, upload_to='batch_photos_or_pdfs/')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tms_batchmedia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BatchParticipantCertificate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=TMS.models.generate_custom_th_urid, editable=False, max_length=36)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('issued_on', models.DateTimeField(blank=True, null=True)),
                ('issue_code', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('attendance_rate', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tms_batchparticipantcertificate',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TPBatchCostBreakup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=TMS.models.generate_custom_th_urid, editable=False, max_length=36)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('centre_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hostel_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fooding_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dresses_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('study_material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('misc_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'db_table': 'tms_tpbatchcostbreakup',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TRClosure',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=TMS.models.generate_custom_th_urid, editable=False, max_length=36)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hra', models.FileField(blank=True, help_text='Upload HRA Document PDF containing required information.', null=True, upload_to='batch_closure_hra/')),
                ('ta_da', models.FileField(blank=True, help_text='Upload TA/DA Document PDF containing required information.', null=True, upload_to='batch_closure_tada/')),
            ],
            options={
                'db_table': 'tms_trclosure',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TRPUserScope',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=TMS.models.generate_custom_th_urid, editable=False, max_length=36)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_role_id', models.BigIntegerField(db_index=True)),
                ('training_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'tms_trpuserscope',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TRTrainer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=TMS.models.generate_custom_th_urid, editable=False, max_length=36)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('attended', models.BooleanField(default=False)),
                ('is_replaced', models.BooleanField(default=False)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tms_trtrainer',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='tpcptocentre',
            options={'managed': True},
        ),
        migrations.RenameField(
            model_name='batchtrainer',
            old_name='participated',
            new_name='attended',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='trainers',
        ),
        migrations.RemoveField(
            model_name='batchtrainer',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='batchtrainer',
            name='status',
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_type',
            field=models.CharField(blank=True, choices=[('SEPARATE', 'Separate Batch'), ('COMBINED', 'Combined Batch')], default='SEPARATE', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='batchtrainer',
            name='is_replaced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batchtrainer',
            name='registered_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('ONGOING', 'Ongoing'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='mastertrainer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.AddIndex(
            model_name='batchbeneficiary',
            index=models.Index(fields=['beneficiary'], name='tms_batchbe_benefic_3d52f8_idx'),
        ),
        migrations.AddIndex(
            model_name='batchtrainer',
            index=models.Index(fields=['batch'], name='tms_batchtr_batch_i_53a87f_idx'),
        ),
        migrations.AddIndex(
            model_name='batchtrainer',
            index=models.Index(fields=['trainer'], name='tms_batchtr_trainer_facc3f_idx'),
        ),
        migrations.AlterModelTable(
            name='batchtrainer',
            table='tms_batchtrainer',
        ),
        migrations.AddField(
            model_name='trtrainer',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser'),
        ),
        migrations.AddField(
            model_name='trtrainer',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser'),
        ),
        migrations.AddField(
            model_name='trtrainer',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TMS.mastertrainer'),
        ),
        migrations.AddField(
            model_name='trtrainer',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_registrations', to='TMS.trainingrequest'),
        ),
        migrations.AddField(
            model_name='trtrainer',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser'),
        ),
        migrations.AddField(
            model_name='trpuserscope',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser'),
        ),
        migrations.AddField(
            model_name='trpuserscope',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser'),
        ),
        migrations.AddField(
            model_name='trpuserscope',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser'),
        ),
        migrations.AddField(
            model_name='trclosure',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches_in_TR', to='TMS.batch'),
        ),
        migrations.AddField(
            model_name='trclosure',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser'),
        ),
        migrations.AddField(
            model_name='trclosure',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser'),
        ),
        migrations.AddField(
            model_name='trclosure',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser'),
        ),
        migrations.AddField(
            model_name='tpbatchcostbreakup',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_cost_breakup', to='TMS.batch'),
        ),
        migrations.AddField(
            model_name='tpbatchcostbreakup',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser'),
        ),
        migrations.AddField(
            model_name='tpbatchcostbreakup',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser'),
        ),
        migrations.AddField(
            model_name='tpbatchcostbreakup',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser'),
        ),
        migrations.AddField(
            model_name='batchparticipantcertificate',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_certificates', to='TMS.batch'),
        ),
        migrations.AddField(
            model_name='batchparticipantcertificate',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser'),
        ),
        migrations.AddField(
            model_name='batchparticipantcertificate',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser'),
        ),
        migrations.AddField(
            model_name='batchparticipantcertificate',
            name='tr_beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='TMS.trbeneficiary'),
        ),
        migrations.AddField(
            model_name='batchparticipantcertificate',
            name='tr_trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='TMS.trtrainer'),
        ),
        migrations.AddField(
            model_name='batchparticipantcertificate',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser'),
        ),
        migrations.AddField(
            model_name='batchmedia',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_pictures', to='TMS.batch'),
        ),
        migrations.AddField(
            model_name='batchmedia',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser'),
        ),
        migrations.AddField(
            model_name='batchmedia',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser'),
        ),
        migrations.AddField(
            model_name='batchmedia',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser'),
        ),
        migrations.AddField(
            model_name='batchmastertrainer',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_trainer_participations', to='TMS.batch'),
        ),
        migrations.AddField(
            model_name='batchmastertrainer',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser'),
        ),
        migrations.AddField(
            model_name='batchmastertrainer',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser'),
        ),
        migrations.AddField(
            model_name='batchmastertrainer',
            name='master_trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TMS.mastertrainer'),
        ),
        migrations.AddField(
            model_name='batchmastertrainer',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser'),
        ),
        migrations.AddField(
            model_name='batchcost',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_costing', to='TMS.batch'),
        ),
        migrations.AddField(
            model_name='batchcost',
            name='batch_expenses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detailed_cost', to='TMS.tpbatchcostbreakup'),
        ),
        migrations.AddField(
            model_name='batchcost',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser'),
        ),
        migrations.AddField(
            model_name='batchcost',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser'),
        ),
        migrations.AddField(
            model_name='batchcost',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser'),
        ),
        migrations.AddField(
            model_name='batchclosurerequest',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_closing', to='TMS.batch'),
        ),
        migrations.AddField(
            model_name='batchclosurerequest',
            name='batch_costing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_cost', to='TMS.batchcost'),
        ),
        migrations.AddField(
            model_name='batchclosurerequest',
            name='batch_pictures',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_media', to='TMS.batchmedia'),
        ),
        migrations.AddField(
            model_name='batchclosurerequest',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser'),
        ),
        migrations.AddField(
            model_name='batchclosurerequest',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser'),
        ),
        migrations.AddField(
            model_name='batchclosurerequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser'),
        ),
        migrations.AddField(
            model_name='batch',
            name='master_trainers',
            field=models.ManyToManyField(blank=True, related_name='master_trainers_for_batch', through='TMS.BatchMasterTrainer', to='TMS.mastertrainer'),
        ),
        migrations.AddField(
            model_name='batch',
            name='trainer',
            field=models.ManyToManyField(blank=True, related_name='trainers_for_batch', through='TMS.BatchTrainer', to='TMS.trtrainer'),
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='trainer',
            field=models.ManyToManyField(blank=True, related_name='trainers_for_training', through='TMS.TRTrainer', to='TMS.mastertrainer'),
        ),
        migrations.AlterField(
            model_name='batchtrainer',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TMS.trtrainer'),
        ),
        migrations.AddIndex(
            model_name='trtrainer',
            index=models.Index(fields=['training'], name='tms_trtrain_trainin_40b44b_idx'),
        ),
        migrations.AddIndex(
            model_name='trtrainer',
            index=models.Index(fields=['trainer'], name='tms_trtrain_trainer_1b6dbe_idx'),
        ),
        migrations.AddIndex(
            model_name='trclosure',
            index=models.Index(fields=['batch'], name='tms_trclosu_batch_i_6c7221_idx'),
        ),
        migrations.AddIndex(
            model_name='tpbatchcostbreakup',
            index=models.Index(fields=['batch'], name='tms_tpbatch_batch_i_f04a16_idx'),
        ),
        migrations.AddIndex(
            model_name='batchparticipantcertificate',
            index=models.Index(fields=['batch'], name='tms_batchpa_batch_i_f84d5f_idx'),
        ),
        migrations.AddIndex(
            model_name='batchparticipantcertificate',
            index=models.Index(fields=['issue_code'], name='tms_batchpa_issue_c_35532e_idx'),
        ),
        migrations.AddIndex(
            model_name='batchmedia',
            index=models.Index(fields=['batch'], name='tms_batchme_batch_i_c7ff8a_idx'),
        ),
        migrations.AddIndex(
            model_name='batchmedia',
            index=models.Index(fields=['category'], name='tms_batchme_categor_440147_idx'),
        ),
        migrations.AddIndex(
            model_name='batchmastertrainer',
            index=models.Index(fields=['batch'], name='tms_batchma_batch_i_92cafd_idx'),
        ),
        migrations.AddIndex(
            model_name='batchmastertrainer',
            index=models.Index(fields=['master_trainer'], name='tms_batchma_master__1a8386_idx'),
        ),
        migrations.AddIndex(
            model_name='batchcost',
            index=models.Index(fields=['batch'], name='tms_batchco_batch_i_34b4d7_idx'),
        ),
        migrations.AddIndex(
            model_name='batchclosurerequest',
            index=models.Index(fields=['batch'], name='tms_batchcl_batch_i_72e3e3_idx'),
        ),
        migrations.AddIndex(
            model_name='batchclosurerequest',
            index=models.Index(fields=['certificates_issued'], name='tms_batchcl_certifi_f18302_idx'),
        ),
    ]
