# Generated by Django 4.2.26 on 2025-12-04 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0002_batchclosurerequest_batchcost_batchmastertrainer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastertrainercertificate',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TMS.trainingtheme'),
        ),
    ]
