# Generated by Django 4.2.26 on 2025-12-09 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mastergeouserscope'),
        ('TMS', '0003_mastertrainercertificate_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='trtrainer',
            name='aadhaar_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Aadhaar No'),
        ),
        migrations.AddField(
            model_name='trtrainer',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.masterblock'),
        ),
        migrations.AddField(
            model_name='trtrainer',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.masterdistrict'),
        ),
        migrations.AddField(
            model_name='trtrainer',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trtrainer',
            name='mobile_no',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Mobile No.'),
        ),
    ]
