# Generated by Django 4.2.26 on 2025-12-11 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mastergeouserscope'),
        ('TMS', '0004_trtrainer_aadhaar_no_trtrainer_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrequest',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.masterblock'),
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.masterdistrict'),
        ),
    ]
