# Generated by Django 4.2.26 on 2025-12-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0005_trainingrequest_block_trainingrequest_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrequest',
            name='status',
            field=models.CharField(choices=[('BATCHING', 'Batching Phase'), ('PENDING', 'Pending Approval'), ('ONGOING', 'Ongoing'), ('REVIEW', 'Review Phase'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='BATCHING', max_length=20),
        ),
    ]
