# Generated by Django 4.2.26 on 2025-12-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0006_alter_trainingrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingrequest',
            name='trainer',
        ),
    ]
