# Generated by Django 4.2.26 on 2025-12-16 16:48

import TMS.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_initial_master_user'),
        ('TMS', '0007_remove_trainingrequest_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='time_of_training',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='BatchSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=TMS.models.generate_custom_th_urid, editable=False, max_length=36)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('schedule_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='TMS.batch')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'db_table': 'tms_batchschedule',
                'managed': True,
                'indexes': [models.Index(fields=['batch'], name='tms_batchsc_batch_i_fd2f0f_idx'), models.Index(fields=['schedule_date'], name='tms_batchsc_schedul_dafee3_idx')],
            },
        ),
    ]
