# Generated by Django 4.2.26 on 2025-12-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0008_batch_time_of_training_batchschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchekycverification',
            name='participant_role',
            field=models.CharField(choices=[('trainer', 'Trainer'), ('trainee', 'Trainee')], max_length=20),
        ),
    ]
