# Generated by Django 4.2.26 on 2025-12-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0009_alter_batchekycverification_participant_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchmedia',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participantattendance',
            name='participant_role',
            field=models.CharField(choices=[('trainer', 'Trainer'), ('trainee', 'Trainee')], max_length=50),
        ),
    ]
