# Generated by Django 4.2.26 on 2025-12-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0010_batchmedia_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tpbatchcostbreakup',
            old_name='misc_cost',
            new_name='total_cost',
        ),
    ]
