# Generated by Django 4.2.26 on 2025-12-17 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0011_rename_misc_cost_tpbatchcostbreakup_total_cost'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='trclosure',
            name='tms_trclosu_batch_i_6c7221_idx',
        ),
        migrations.RemoveField(
            model_name='batchclosurerequest',
            name='batch_pictures',
        ),
        migrations.RemoveField(
            model_name='trclosure',
            name='batch',
        ),
        migrations.AddField(
            model_name='batchcost',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TR_of_batch', to='TMS.trainingrequest'),
        ),
        migrations.AddField(
            model_name='trclosure',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TR_closure', to='TMS.trainingrequest'),
        ),
        migrations.AlterField(
            model_name='batchclosurerequest',
            name='batch_costing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_cost', to='TMS.tpbatchcostbreakup'),
        ),
        migrations.AddIndex(
            model_name='trclosure',
            index=models.Index(fields=['training'], name='tms_trclosu_trainin_fd3be4_idx'),
        ),
    ]
