# Generated by Django 4.2.26 on 2025-12-25 06:23

import TMS.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_initial_master_user'),
        ('TMS', '0012_remove_trclosure_tms_trclosu_batch_i_6c7221_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=TMS.models.generate_custom_th_urid, editable=False, max_length=36)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('BMM_SIGNED', 'Signed by BMMU'), ('DMM_SIGNED', 'Signed by DMMU'), ('SMM_SIGNED', 'Signed by SMMU')], default='DRAFT', max_length=20)),
                ('report_file', models.FileField(blank=True, help_text='Upload Batch Report Document PDF.', null=True, upload_to='batch_reports/')),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_report', to='TMS.batch')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'db_table': 'tms_batchreport',
                'managed': True,
                'indexes': [models.Index(fields=['batch'], name='tms_batchre_batch_i_7348df_idx')],
            },
        ),
    ]
