# Generated by Django 4.2.26 on 2026-04-15 04:26

import TMS.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0013_batchreport'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tpcptocentre',
            unique_together={('contact_person', 'allocated_centre')},
        ),
        migrations.CreateModel(
            name='BeneficiaryAttendanceSummary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=TMS.models.generate_custom_th_urid, editable=False, max_length=36)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_training_days', models.PositiveIntegerField(default=0)),
                ('days_present', models.PositiveIntegerField(default=0)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_dropout', models.BooleanField(default=False)),
                ('is_successful', models.BooleanField(default=False, help_text='True if attendance is >= 80% and participant is NOT a dropout.')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_summaries', to='TMS.batch')),
                ('batch_beneficiary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summary', to='TMS.batchbeneficiary')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('training_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_attendance_summaries', to='TMS.trainingrequest')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'db_table': 'tms_beneficiaryattendancesummary',
                'managed': True,
                'indexes': [models.Index(fields=['batch'], name='tms_benefic_batch_i_eb5176_idx'), models.Index(fields=['training_request'], name='tms_benefic_trainin_a9b4b2_idx'), models.Index(fields=['is_dropout'], name='tms_benefic_is_drop_6c9380_idx'), models.Index(fields=['is_successful'], name='tms_benefic_is_succ_33af55_idx')],
            },
        ),
    ]
