# Generated by Django 4.2.26 on 2026-04-15 06:18

import TMS.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0014_alter_tpcptocentre_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPartnerAchievement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=TMS.models.generate_custom_th_urid, editable=False, max_length=36)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('batches_completed', models.PositiveIntegerField(default=0)),
                ('financial_year', models.CharField(blank=True, max_length=9, null=True, verbose_name='Financial year')),
                ('date_achieved', models.DateField(blank=True, null=True)),
                ('assigned_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='TMS.trainingpartnertargets')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.masterdistrict')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='TMS.trainingpartner')),
                ('training_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='TMS.trainingplan')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'db_table': 'tms_trainingpartnerachievement',
                'managed': True,
                'indexes': [models.Index(fields=['partner'], name='tms_trainin_partner_9bb743_idx'), models.Index(fields=['assigned_target'], name='tms_trainin_assigne_0daf14_idx'), models.Index(fields=['date_achieved'], name='tms_trainin_date_ac_248e65_idx')],
            },
        ),
    ]
