# Generated by Django 4.2.26 on 2026-04-15 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0015_trainingpartnerachievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trclosure',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='trclosure',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='trclosure',
            name='training',
        ),
        migrations.RemoveField(
            model_name='trclosure',
            name='updated_by',
        ),
        migrations.RemoveIndex(
            model_name='batchcost',
            name='tms_batchco_batch_i_34b4d7_idx',
        ),
        migrations.RenameField(
            model_name='batchcost',
            old_name='tp_part_cost',
            new_name='exposure_visit_cost',
        ),
        migrations.RenameField(
            model_name='batchcost',
            old_name='trainer_part_cost',
            new_name='field_visit_cost',
        ),
        migrations.RenameField(
            model_name='tpbatchcostbreakup',
            old_name='centre_cost',
            new_name='hra',
        ),
        migrations.RenameField(
            model_name='tpbatchcostbreakup',
            old_name='dresses_cost',
            new_name='ta_da',
        ),
        migrations.RemoveField(
            model_name='batchcost',
            name='batch_expenses',
        ),
        migrations.RemoveField(
            model_name='tpbatchcostbreakup',
            name='fooding_cost',
        ),
        migrations.RemoveField(
            model_name='tpbatchcostbreakup',
            name='hostel_cost',
        ),
        migrations.RemoveField(
            model_name='tpbatchcostbreakup',
            name='study_material_cost',
        ),
        migrations.AddField(
            model_name='batchcost',
            name='grand_total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='batchcost',
            name='is_exposure_visit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batchcost',
            name='is_field_visit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tpbatchcostbreakup',
            name='batch_beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_breakup', to='TMS.batchbeneficiary'),
        ),
        migrations.AddField(
            model_name='tpbatchcostbreakup',
            name='batch_trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_breakup', to='TMS.batchtrainer'),
        ),
        migrations.AddField(
            model_name='tpbatchcostbreakup',
            name='participant_type',
            field=models.CharField(choices=[('BENEFICIARY', 'Beneficiary'), ('TRAINER', 'Trainer')], default='BENEFICIARY', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batchclosurerequest',
            name='batch',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='batch_closing', to='TMS.batch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batchclosurerequest',
            name='batch_costing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closure_requests', to='TMS.batchcost'),
        ),
        migrations.AlterField(
            model_name='batchcost',
            name='batch',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='batch_costing', to='TMS.batch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tpbatchcostbreakup',
            name='batch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='participant_costs', to='TMS.batch'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='tpbatchcostbreakup',
            index=models.Index(fields=['batch_beneficiary'], name='tms_tpbatch_batch_b_e7489f_idx'),
        ),
        migrations.AddIndex(
            model_name='tpbatchcostbreakup',
            index=models.Index(fields=['batch_trainer'], name='tms_tpbatch_batch_t_db93c5_idx'),
        ),
        migrations.DeleteModel(
            name='TRClosure',
        ),
    ]
