# Generated by Django 4.2.26 on 2026-04-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0016_remove_trclosure_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('ONGOING', 'Ongoing'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('REVIEW', 'Under Review'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=30),
        ),
    ]
