# Generated by Django 4.2.26 on 2026-04-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0017_alter_batch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
