# Generated by Django 4.2.26 on 2026-04-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0018_batch_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrequest',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
