# Generated by Django 4.2.26 on 2026-04-22 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0019_trainingrequest_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryattendancesummary',
            name='batch_trainer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summary', to='TMS.batchtrainer'),
        ),
        migrations.AlterField(
            model_name='beneficiaryattendancesummary',
            name='batch_beneficiary',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summary', to='TMS.batchbeneficiary'),
        ),
    ]
