# Generated by Django 4.2.26 on 2026-04-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0020_beneficiaryattendancesummary_batch_trainer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingpartner',
            name='tp_short_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Short Name'),
        ),
    ]
