# Generated by Django 4.2.26 on 2026-04-24 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0021_trainingpartner_tp_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMSFirstLoginTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_login_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('must_change_password', models.BooleanField(default=True)),
                ('master_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tms_first_login', to='core.masteruser')),
            ],
            options={
                'db_table': 'tms_first_login_tracker',
                'managed': True,
            },
        ),
    ]
