# Generated by Django 4.2.26 on 2026-05-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0022_tmsfirstlogintracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='is_achievement_counted',
            field=models.BooleanField(default=False),
        ),
    ]
