# Generated by Django 4.2.26 on 2026-06-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0023_batch_is_achievement_counted'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrequest',
            name='financial_year',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Financial year'),
        ),
    ]
