# Generated by Django 4.2.26 on 2026-06-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0024_trainingrequest_financial_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='financial_year',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Financial year'),
        ),
    ]
