# Generated by Django 4.2.26 on 2026-06-15 07:05

import TMS.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0025_batch_financial_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='trbeneficiary',
            name='CB_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trtrainer',
            name='CB_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CombinedBatchSummary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=TMS.models.generate_custom_th_urid, editable=False, max_length=36)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_districts_covered', models.PositiveIntegerField(default=0, verbose_name='Total Unique Districts')),
                ('total_blocks_covered', models.PositiveIntegerField(default=0, verbose_name='Total Unique Blocks')),
                ('total_beneficiaries', models.PositiveIntegerField(default=0, verbose_name='Total Beneficiaries in Combined Batch')),
                ('total_trainers', models.PositiveIntegerField(default=0, verbose_name='Total Trainers in Combined Batch')),
                ('notes', models.TextField(blank=True, null=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='combined_summary', to='TMS.batch')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'db_table': 'tms_combinedbatchsummary',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CombinedBatchDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=TMS.models.generate_custom_th_urid, editable=False, max_length=36)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('participant_type', models.CharField(choices=[('BENEFICIARY', 'Beneficiary'), ('TRAINER', 'Master Trainer')], max_length=20)),
                ('participant_count', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.masterblock')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.masterdistrict')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_details', to='TMS.combinedbatchsummary')),
                ('training_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combined_batch_allocations', to='TMS.trainingrequest')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'db_table': 'tms_combinedbatchdetail',
                'managed': True,
                'indexes': [models.Index(fields=['summary'], name='tms_combine_summary_879c6c_idx'), models.Index(fields=['district'], name='tms_combine_distric_c55743_idx'), models.Index(fields=['block'], name='tms_combine_block_i_36674f_idx'), models.Index(fields=['participant_type'], name='tms_combine_partici_443a2b_idx')],
            },
        ),
    ]
