# Generated by Django 4.2.26 on 2026-06-29 08:27

import TMS.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0026_trbeneficiary_cb_selected_trtrainer_cb_selected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictTP',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=TMS.models.generate_custom_th_urid, editable=False, max_length=36)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active_dtp', models.BooleanField(default=True, verbose_name='Is Active District TP')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='district_tp_assignments', to='core.masterdistrict')),
                ('master_user', models.ForeignKey(blank=True, db_column='user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dtp_account', to='core.masteruser')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_nodes', to='TMS.trainingpartner')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'db_table': 'tms_districttp',
                'managed': True,
                'indexes': [models.Index(fields=['partner'], name='tms_distric_partner_2a7b05_idx'), models.Index(fields=['district'], name='tms_distric_distric_a63c62_idx'), models.Index(fields=['master_user'], name='tms_distric_user_id_d8e12f_idx')],
                'unique_together': {('partner', 'district')},
            },
        ),
    ]
