# Generated by Django 4.2.26 on 2026-07-01 06:13

import TMS.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0027_districttp'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchBlockCoverage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=TMS.models.generate_custom_th_urid, editable=False, max_length=36)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('participant_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'tms_batchblockcoverage',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='combinedbatchdetail',
            name='block',
        ),
        migrations.RemoveField(
            model_name='combinedbatchdetail',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='combinedbatchdetail',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='combinedbatchdetail',
            name='district',
        ),
        migrations.RemoveField(
            model_name='combinedbatchdetail',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='combinedbatchdetail',
            name='training_request',
        ),
        migrations.RemoveField(
            model_name='combinedbatchdetail',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='combinedbatchsummary',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='combinedbatchsummary',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='combinedbatchsummary',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='combinedbatchsummary',
            name='updated_by',
        ),
        migrations.RemoveIndex(
            model_name='batch',
            name='tms_batch_request_8c0fd0_idx',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='request',
        ),
        migrations.AddField(
            model_name='batch',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_batches', to='TMS.trainingpartner'),
        ),
        migrations.AddField(
            model_name='batch',
            name='training_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_batches', to='TMS.trainingplan'),
        ),
        migrations.AddField(
            model_name='batchbeneficiary',
            name='training_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_beneficiary_mappings', to='TMS.trainingrequest'),
        ),
        migrations.AddField(
            model_name='batchtrainer',
            name='training_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_trainer_mappings', to='TMS.trainingrequest'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['training_plan'], name='tms_batch_trainin_74addd_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['partner'], name='tms_batch_partner_c33623_idx'),
        ),
        migrations.AddIndex(
            model_name='batchbeneficiary',
            index=models.Index(fields=['training_request'], name='tms_batchbe_trainin_b993b6_idx'),
        ),
        migrations.AddIndex(
            model_name='batchtrainer',
            index=models.Index(fields=['training_request'], name='tms_batchtr_trainin_900bda_idx'),
        ),
        migrations.DeleteModel(
            name='CombinedBatchDetail',
        ),
        migrations.DeleteModel(
            name='CombinedBatchSummary',
        ),
        migrations.AddField(
            model_name='batchblockcoverage',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_coverages', to='TMS.batch'),
        ),
        migrations.AddField(
            model_name='batchblockcoverage',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered_batches', to='core.masterblock'),
        ),
        migrations.AddField(
            model_name='batchblockcoverage',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser'),
        ),
        migrations.AddField(
            model_name='batchblockcoverage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser'),
        ),
        migrations.AddField(
            model_name='batchblockcoverage',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser'),
        ),
        migrations.AddIndex(
            model_name='batchblockcoverage',
            index=models.Index(fields=['batch'], name='tms_batchbl_batch_i_30103f_idx'),
        ),
        migrations.AddIndex(
            model_name='batchblockcoverage',
            index=models.Index(fields=['block'], name='tms_batchbl_block_i_fed803_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='batchblockcoverage',
            unique_together={('batch', 'block')},
        ),
    ]
