# Generated by Django 4.2.26 on 2026-07-01 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0028_batchblockcoverage_remove_combinedbatchdetail_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.masterblock'),
        ),
        migrations.AddField(
            model_name='batch',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.masterdistrict'),
        ),
    ]
