# Generated by Django 4.2.26 on 2026-07-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0029_batch_block_batch_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='participant_type',
            field=models.CharField(blank=True, choices=[('BENEFICIARY', 'Beneficiary'), ('TRAINER', 'Master Trainer')], max_length=20, null=True, verbose_name='Applicable For'),
        ),
    ]
