# Generated by Django 4.2.26 on 2026-07-05 06:51

import TMS.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0030_batch_participant_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=TMS.models.generate_custom_th_urid, editable=False, max_length=36)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('ONGOING', 'Ongoing'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('REVIEW', 'Under Review'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], max_length=30)),
                ('remarks', models.TextField(blank=True, help_text='Stores rejection reasons or automated system tracking remarks.', null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='TMS.batch')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'db_table': 'tms_batchhistory',
                'ordering': ['-created_at'],
                'managed': True,
                'indexes': [models.Index(fields=['batch'], name='tms_batchhi_batch_i_7daed7_idx'), models.Index(fields=['status'], name='tms_batchhi_status_7a8d0d_idx'), models.Index(fields=['created_at'], name='tms_batchhi_created_47be60_idx')],
            },
        ),
    ]
