# Generated by Django 4.2.26 on 2026-07-14 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0031_batchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastertrainer',
            name='induction',
            field=models.BooleanField(default=False, verbose_name='Induction (YES/NO)'),
        ),
        migrations.AddField(
            model_name='mastertrainer',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_trainers', to='TMS.trainingtheme'),
        ),
        migrations.AddField(
            model_name='mastertrainer',
            name='tot_farm_lh',
            field=models.BooleanField(default=False, verbose_name='TOT FARM LH (YES/NO)'),
        ),
        migrations.AddField(
            model_name='mastertrainer',
            name='tot_lokos',
            field=models.BooleanField(default=False, verbose_name='TOT LOKOS (YES/NO)'),
        ),
        migrations.AddField(
            model_name='mastertrainer',
            name='tot_mffi',
            field=models.BooleanField(default=False, verbose_name='TOT MFFI (YES/NO)'),
        ),
        migrations.AddField(
            model_name='mastertrainer',
            name='tot_model_clf',
            field=models.BooleanField(default=False, verbose_name='TOT MODEL CLF (YES/NO)'),
        ),
        migrations.AddField(
            model_name='mastertrainer',
            name='tot_non_farm_lh',
            field=models.BooleanField(default=False, verbose_name='TOT NON FARM LH (YES/NO)'),
        ),
        migrations.AddField(
            model_name='mastertrainer',
            name='tot_sisd',
            field=models.BooleanField(default=False, verbose_name='TOT SISD (YES/NO)'),
        ),
        migrations.AddField(
            model_name='mastertrainer',
            name='tot_smcb',
            field=models.BooleanField(default=False, verbose_name='TOT SMCB (YES/NO)'),
        ),
    ]
