# Generated by Django 4.2.26 on 2026-07-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0032_mastertrainer_induction_mastertrainer_theme_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tpcptocentre',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='tpcptocentre',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('contact_person', 'allocated_centre'), name='unique_active_tpcp_centre'),
        ),
    ]
