# Generated by Django 4.2.26 on 2026-07-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0033_alter_tpcptocentre_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='level',
            field=models.CharField(blank=True, choices=[('BLOCK', 'Block'), ('DISTRICT', 'District'), ('STATE', 'State')], default='BLOCK', max_length=50, null=True),
        ),
    ]
