# Generated by Django 4.2.26 on 2026-07-24 13:08

import TMS.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0034_batch_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=TMS.models.generate_custom_th_urid, editable=False, max_length=36)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'db_table': 'tms_bank',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=TMS.models.generate_custom_th_urid, editable=False, max_length=36)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('employment_type', models.CharField(blank=True, max_length=255, null=True)),
                ('doj', models.DateTimeField(blank=True, null=True)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('marital_status', models.CharField(max_length=50)),
                ('perma_address', models.TextField(blank=True, null=True, verbose_name='Permanent Address')),
                ('current_address', models.TextField(blank=True, null=True, verbose_name='Current Address')),
                ('program', models.CharField(max_length=255)),
                ('social_category', models.CharField(blank=True, max_length=255, null=True)),
                ('aadhar', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(100000000000), django.core.validators.MaxValueValidator(999999999999)])),
                ('pan', models.CharField(max_length=255)),
                ('uan', models.CharField(max_length=255)),
                ('epf', models.CharField(max_length=255)),
                ('esic', models.CharField(max_length=255)),
                ('bank_account_no', models.CharField(max_length=255)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TMS.bank')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.masterblock')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.masterdistrict')),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_theme', to='TMS.trainingtheme')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'db_table': 'tms_staffprofile',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='beneficiaryattendancesummary',
            name='batch_master_trainer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summary', to='TMS.batchmastertrainer'),
        ),
        migrations.AddField(
            model_name='tpbatchcostbreakup',
            name='batch_mastertrainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_breakup', to='TMS.batchmastertrainer'),
        ),
        migrations.AddField(
            model_name='tpbatchcostbreakup',
            name='lm_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tpbatchcostbreakup',
            name='trainer_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tpbatchcostbreakup',
            name='training_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='trainingpartnertargets',
            name='budget_head',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='participant_type',
            field=models.CharField(blank=True, choices=[('BENEFICIARY', 'Beneficiary'), ('TRAINER', 'Master Trainer'), ('STAFF', 'Staff')], max_length=20, null=True, verbose_name='Applicable For'),
        ),
        migrations.AlterField(
            model_name='tpbatchcostbreakup',
            name='participant_type',
            field=models.CharField(choices=[('BENEFICIARY', 'Beneficiary'), ('TRAINER', 'Trainer'), ('MASTER_TRAINER', 'Master Trainer'), ('STAFF', 'Staff')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='training_type',
            field=models.CharField(choices=[('BENEFICIARY', 'Beneficiary'), ('TRAINER', 'Master Trainer'), ('STAFF', 'Staff')], max_length=20, verbose_name='Applicable For'),
        ),
        migrations.CreateModel(
            name='TRStaff',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=TMS.models.generate_custom_th_urid, editable=False, max_length=36)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('attended', models.BooleanField(default=False)),
                ('is_replaced', models.BooleanField(default=False)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('CB_selected', models.BooleanField(default=False)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.masterblock')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.masterdistrict')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TMS.staffprofile')),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trstaff_theme', to='TMS.trainingtheme')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_registrations', to='TMS.trainingrequest')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'db_table': 'tms_trstaff',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BatchStaff',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=TMS.models.generate_custom_th_urid, editable=False, max_length=36)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('attended', models.BooleanField(default=False)),
                ('is_replaced', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_participations', to='TMS.batch')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TMS.trstaff')),
                ('training_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_staff_mappings', to='TMS.trainingrequest')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'db_table': 'tms_batchstaff',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BankIFSC',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=TMS.models.generate_custom_th_urid, editable=False, max_length=36)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ifsc_code', models.CharField(max_length=255)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BANK_IFSC', to='TMS.bank')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'db_table': 'tms_bankifsc',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=TMS.models.generate_custom_th_urid, editable=False, max_length=36)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=255)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BANK_BRANCH', to='TMS.bank')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
            ],
            options={
                'db_table': 'tms_bankbranch',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='staff_for_batch', through='TMS.BatchStaff', to='TMS.trstaff'),
        ),
        migrations.AddField(
            model_name='batchparticipantcertificate',
            name='tr_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='TMS.trstaff'),
        ),
        migrations.AddField(
            model_name='beneficiaryattendancesummary',
            name='batch_staff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summary', to='TMS.batchstaff'),
        ),
        migrations.AddField(
            model_name='tpbatchcostbreakup',
            name='batch_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_breakup', to='TMS.batchstaff'),
        ),
        migrations.AddIndex(
            model_name='trstaff',
            index=models.Index(fields=['training'], name='tms_trstaff_trainin_f15f93_idx'),
        ),
        migrations.AddIndex(
            model_name='trstaff',
            index=models.Index(fields=['staff'], name='tms_trstaff_staff_i_74e58e_idx'),
        ),
        migrations.AddIndex(
            model_name='trstaff',
            index=models.Index(fields=['theme'], name='tms_trstaff_theme_i_dbc6a6_idx'),
        ),
        migrations.AddIndex(
            model_name='trstaff',
            index=models.Index(fields=['district'], name='tms_trstaff_distric_9ea895_idx'),
        ),
        migrations.AddIndex(
            model_name='trstaff',
            index=models.Index(fields=['block'], name='tms_trstaff_block_i_5581c9_idx'),
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['employee_id'], name='tms_staffpr_employe_42c554_idx'),
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['theme'], name='tms_staffpr_theme_i_a402fb_idx'),
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['aadhar'], name='tms_staffpr_aadhar_0080d9_idx'),
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['district'], name='tms_staffpr_distric_c14a1c_idx'),
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['block'], name='tms_staffpr_block_i_96ae9c_idx'),
        ),
        migrations.AddIndex(
            model_name='batchstaff',
            index=models.Index(fields=['batch'], name='tms_batchst_batch_i_353410_idx'),
        ),
        migrations.AddIndex(
            model_name='batchstaff',
            index=models.Index(fields=['staff'], name='tms_batchst_staff_i_22490b_idx'),
        ),
        migrations.AddIndex(
            model_name='batchstaff',
            index=models.Index(fields=['training_request'], name='tms_batchst_trainin_7cf2a3_idx'),
        ),
    ]
