# Generated by Django 4.2.26 on 2026-07-24 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0035_bank_staffprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='bank_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TMS.bankbranch'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='bank_ifsc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TMS.bankifsc'),
        ),
    ]
