# Generated by Django 4.2.26 on 2026-08-13 08:40

import TMS.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0036_staffprofile_bank_branch_staffprofile_bank_ifsc'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterTrainerProfileStatus',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('TH_urid', models.CharField(db_column='TH_urid', default=TMS.models.generate_custom_th_urid, editable=False, max_length=36)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Verification Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('verified_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('trainer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_status', to='TMS.mastertrainer')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.masteruser')),
                ('verified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_mt_profiles', to='core.masteruser')),
            ],
            options={
                'db_table': 'tms_mastertrainerprofilestatus',
                'managed': True,
                'indexes': [models.Index(fields=['status'], name='tms_mastert_status_e818f4_idx'), models.Index(fields=['trainer'], name='tms_mastert_trainer_8ec67b_idx')],
            },
        ),
    ]
