# Generated by Django 4.2.26 on 2026-08-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0038_learningmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='is_old',
            field=models.BooleanField(db_column='is_old', default=False),
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='is_old',
            field=models.BooleanField(db_column='is_old', default=False),
        ),
    ]
