# Generated by Django 4.2.26 on 2026-09-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0039_batch_is_old_trainingrequest_is_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='trbeneficiary',
            name='lokos_shg_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trbeneficiary',
            name='relation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trbeneficiary',
            name='relation_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
