# Generated by Django 4.2.26 on 2026-10-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0040_trbeneficiary_lokos_shg_name_trbeneficiary_relation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertrainer',
            name='designation',
            field=models.CharField(blank=True, choices=[('BRP', 'BRP'), ('DRP', 'DRP'), ('SRP', 'SRP'), ('NRP', 'NRP'), ('TSA', 'TSA'), ('BMMU', 'BMMU'), ('DMMU', 'DMMU'), ('SMMU', 'SMMU')], db_index=True, max_length=10, null=True, verbose_name='Designation'),
        ),
    ]
